"""empty message

Revision ID: 597cfb1f4046
Revises: 
Create Date: 2017-02-16 17:17:40.229158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597cfb1f4046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('stu_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_students_stu_id'), 'students', ['stu_id'], unique=True)
    op.drop_index('ix_students_sut_id', table_name='students')
    op.drop_column('students', 'sut_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('sut_id', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_students_sut_id', 'students', ['sut_id'], unique=1)
    op.drop_index(op.f('ix_students_stu_id'), table_name='students')
    op.drop_column('students', 'stu_id')
    # ### end Alembic commands ###
